language: java

before_install:
  - echo 'yes' | sudo add-apt-repository ppa:ondrej/php5-oldstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-cli php5-curl php5-memcached php5-imagick php5-dev php-pear
  - sudo pecl install mongo
  - echo "extension=mongo.so" | sudo tee /etc/php5/cli/php.ini
  - php -v
  - curl https://getcomposer.org/installer | php
  - chmod +x composer.phar
  - sudo ln -s "$PWD/composer.phar" /usr/local/bin/composer
  - ln -s "$TRAVIS_BUILD_DIR/test/travis-config.json" "$TRAVIS_BUILD_DIR/misc/test-config.json"
services:
  - mongodb
script:
  - "$TRAVIS_BUILD_DIR/test/travis.sh"
env:
  - IMBOCLIENT_RUN_INTEGRATION_TESTS=1
